### ISSUE TITLE
how to determine the number of layers

### ISSUE THREAD

**Issue by Shuwan-Wang** [stefanradev93/BayesFlow#107]
Hi Stefan et al.,

I am curious that how did you determine the number of layers for the different models?

In the simulation studies, you mentioned like 6-10 ACBs should be enough for moderate model setup. So instead of trying different #of ACBs and keep stacking up, do you have any suggestions/better way?

Thanks!
Best,
Shuwan

**Comment by stefanradev93** [comment]
Hey Shuwan,

There is no established systematic way. Bayesian optimization would be one, but it may be an overkill to just testing out a few variants.
Stefan
