### ISSUE TITLE
Question about handling missing data

### ISSUE THREAD

**Issue by Aceticia** [stefanradev93/BayesFlow#119]
Hi, I'm wondering whether it is of any interest to include the ability for sequential networks or invariant networks to handle missing data. Some of our subjects have only partial data, but it would be a huge waste to just remove them. From the documentation, it's not straightforward to handle missing data. If this is something the maintainers feel like would be useful I am down to help with implementing this.

**Comment by marvinschmitt** [comment]
Hi,

Thanks for reaching out. I agree that missing data is an essential aspect of applied analyses. There has been some work on missing data in SBI, and we should make handling missing data easier in BayesFlow.

Would you mind opening a topic in the recently established BayesFlow Forums at https://discuss.bayesflow.org/? Let's talk about the details there.
