### ISSUE TITLE
Use Training Strategy Pattern in Trainer

### ISSUE THREAD

**Issue by LarsKue** [stefanradev93/BayesFlow#125]
The current implementation of `bayesflow.trainers.Trainer` implements several training strategies in one large class. This can be problematic for both maintainers and users, since

1. Implementing a new strategy from outside `bayesflow` requires inheriting from the `Trainer` class
2. Modifying small parts of a strategy outside of its input parameters can be difficult or impossible
3. Maintaining a mental overview over the Trainer functionality is impeded.

We can remedy these issues by implementing the trainer strategies explicitly as their own concept, and following [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) in the Trainer class.

**Comment by stefanradev93** [comment]
That's a very important one! Especially since we want to add some new strategies in the process.

**Comment by LarsKue** [comment]
Superceded by the removal of the trainer object
