### ISSUE TITLE
Loss not shown in keras output

### ISSUE THREAD

**Issue by stefanradev93** [stefanradev93/BayesFlow#168]
The upcoming keras 3.0 amortizer does not show any losses in keras output and progress bar. This is urgently needed for the streamlined-backend branch.

**Comment by han-ol** [comment]
Not sure if my setup matches what you are facing. However, for me adding the loss explicitly in `network.compute_metrics()` solves this.

Proposed change within [coupling_flow/couplings/all_in_one_coupling.py](https://github.com/stefanradev93/BayesFlow/blob/streamlined-backend/bayesflow/experimental/networks/coupling_flow/couplings/all_in_one_coupling.py):

```python
def compute_metrics(self, x, y, y_pred, **kwargs):
    metrics = dict(loss=self.compute_loss(x, y, y_pred, **kwargs))
    
    return metrics
```

with this amortizer class, calling `amortizer.fit()` results in


```shell
Epoch 1/2
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 105ms/step - inference/loss: 2.9389
Epoch 2/2
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 104ms/step - inference/loss: 1.8689
```

**Comment by LarsKue** [comment]
Solved by simply calling `base_metrics = super().compute_metrics(...)` and then merging our extra metrics with those.
