### ISSUE TITLE
Best practice recommendations for saving trained networks

### ISSUE THREAD

**Issue by zijianwang2000** [stefanradev93/BayesFlow#18]
Hi Stefan,

do you have any recommendations for how to best store the trained networks when using the parameter estimation workflow notebook?

Best regards
Zijian

**Comment by stefanradev93** [comment]
Hi Zijian,

you can just use the argument `checkpoint_path` when creating a `Trainer` instance.

Cheers,
Stefan

**Comment by zijianwang2000** [comment]
Thanks a lot!

Best regards
Zijian
