### ISSUE TITLE
handing of missing data 

### ISSUE THREAD

**Issue by timktsang** [stefanradev93/BayesFlow#20]
I would like to ask what should we do for missing data in BayesFlow

E.g. I have a dataset X with N row and 5 columns, and they are i.i.d., and 

X [ I , j ] ~ binomial (1, params[ j ] ) , hence I got five parameters , j = 0, 1, 2, 3, 4

say if for some reasons, X[ I , j ] is missing when I %% 5 = j 

what should I put in X [ I , j ] in order to get correct posterior? 

I tried putting value like -1 will not get correct results

I tried the version without missing and the output posterior is reasonable.

Thank you.

**Comment by stefanradev93** [comment]
Hi Tim,

you should train the networks under the assumption of missing data. For instance, you could simulate your data using a varying missing rate for each simulation. In this case, the networks will see the -1 during training and know to ignore it when recovering the posterior.

**Comment by timktsang** [comment]
Thanks Stefan. I tried, and yes, it works.
