### ISSUE TITLE
Flow Matching: Allow passing class as subnet (2.0 version)

### ISSUE THREAD

**Issue by vpratz** [stefanradev93/BayesFlow#200]
This is probably already planned: `FlowMatching` currently only accepts strings for the `subnet` argument. Allowing classes as well would help with modularity, as it enables easily plugging in custom networks for power users, without sacrificing ease of use for others.
Handling the case in `utils.find_network` and initializing the class there might be sufficient to enable this.

**Comment by marvinschmitt** [comment]
I like the idea and second the proposal. 

Would you mind drafting a PR that implements this? Based on your description it should be quite straightforward.

**Comment by marvinschmitt** [comment]
closed by #201
