### ISSUE TITLE
offline training with varying sample size

### ISSUE THREAD

**Issue by timktsang** [stefanradev93/BayesFlow#21]
In tutorial -- online training, I saw that we could put prior_N function to allow for varying sample size. I would like to ask how we can do the same for offline training? what should be the input of sim_data in the trainer.train_offine function? As suggested by others, this could be very helpful since we can use other software to simulate data like C++

Thank you very much!

**Comment by stefanradev93** [comment]
Hi Tim,

currently, it is not possible to have varying N for offline training but it will be supported in the future update. For now, you can try "hacking" it by creating a generator which processes the pre-simulated data and acts as a generative model which takes a random sub-sample at each iteration.
