### ISSUE TITLE
Summary network for time series data

### ISSUE THREAD

**Issue by zijianwang2000** [stefanradev93/BayesFlow#24]
Hi Stefan,

I would like to use a summary network to handle time series data coming from an ODE model. It is a toy model with one or two observed state(s), n_obs=31 fixed for each dataset and the described dynamics is very simple. From your experience, do you maybe have a proposal for a summary network that I should try out? To me, it is more important that the network is sufficient to capture all the relevant information than having the optimal output size. Thanks a lot!

Best regards
Zijian

**Comment by zijianwang2000** [comment]
Just to make sure (since I'm not super familiar with building ML models with keras yet), do you mean like the following:
```python
class LSTM_Network(tf.keras.Model):
    """
    Implements an LSTM summary network to summarize time-series data generated from the CR model.
    """

    def __init__(self):
        super(LSTM_Network, self).__init__()

        self.lstm_part = Sequential([LSTM(64)])

    def call(self, x):

        out = self.lstm_part(x)
        return out
```

**Comment by stefanradev93** [comment]
You can do that, but more simply, you can just do:

`summary_net = LSTM(64)`

**Comment by zijianwang2000** [comment]
Thanks! And the number of hidden units 64 comes from the dataset dimension (2, 31) so that we can be sure that the LSTM network is sufficient to preserve all the information (64 \geq 2*31)?

**Comment by stefanradev93** [comment]
Exactly. Note, that tensorflow would require that your simulated data has the shape `(batch_size, time_steps = 31, data_dim = 2)`.

**Comment by zijianwang2000** [comment]
Alright, thanks a lot!
