### ISSUE TITLE
limit of training data for input.

### ISSUE THREAD

**Issue by timktsang** [stefanradev93/BayesFlow#26]
Hi there,

May I ask if there is any limit for input training data?

for example I want to put 50000 simulated data in the following size: (50000,3000,45)

when I try to run 

%%time losses = trainer.train_offline(epochs=100, batch_size=64, params=true_params, sim_data=x)

I got error:

InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.

is that because of my GPU limit (20G)? 

actually all (3000,45) are integer only, is it possible to specify integer array to save ram?

**Comment by stefanradev93** [comment]
You would need more than 25GB of GPU memory to fit only the simulated data set in memory (excluding network parameters). I suggest you store your simulated data into much smaller chunks which you can then sequentially read from disk and avoid memory blowup.

**Comment by timktsang** [comment]
thanks for answering! I changed the data format to aggregated data and it works better now
