### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by yannikschaelte** [stefanradev93/BayesFlow#54]
I suggest adding a contribution guide (see e.g. [this doc](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)) to make it easier to contribute to the tool. In particular, this should cover:

* From which branch to start (Development?)
* The standard workflow (make issue, fork, make sure tests pass + add new ones, create pull request)

**Comment by stefanradev93** [comment]
Good idea! I will work on the doc.

**Comment by stefanradev93** [comment]
Added https://github.com/stefanradev93/BayesFlow/blob/Development/CONTRIBUTING.md

**Comment by yannikschaelte** [comment]
Awesome, that helps me already :)
