### ISSUE TITLE
Data / Parameters Tranformations

### ISSUE THREAD

**Issue by stefanradev93** [stefanradev93/BayesFlow#6]
Add functionality for providing data/parameter transformations, such as scaling, normalization, noise injection, etc. to the trainers.

**Comment by marvinschmitt** [comment]
We discussed that the transform functionality will be added directly to the generative model. Transforms can be specified as 

- a single callable: same transform for all models
- a list of callables with length `n_models`: separate transform for each model

**Comment by marvinschmitt** [comment]
implemented in 8a18be1be961dceca82be4e1af42961421463cef

in addition to https://github.com/stefanradev93/BayesFlow/issues/6#issuecomment-822478276, any item in the list can be either callable or `None`. `None` equals the identity function (no transform for that model)
