### ISSUE TITLE
x ~ scale * N(theta, 1) or x ~ N(theta, scale)? 🤔

### ISSUE THREAD

**Issue by niels-leif-bracher** [stefanradev93/BayesFlow#66]
Hello 👋 ,
I was trying to understand the benchmark datasets used to evaluate BayesFlow's performance. One thing that I noted for a couple of datasets is the scaling factor in front of the distribution for sampling the observations. One example is linked below, which is the T.2 task from the sbib paper. 
Generating points for the original task would look like this:
theta ~ scale * N(0,1) = N(0, scale * 1)
x ~ N(theta, scale * 1)
with scale being the same for both distributions i.e., scale=0.1

Now your implementation is:
theta ~ scale * N(0,1) (same as above)
x ~ scale * N(theta, 1) = N(scale * theta, scale * 1)
which is equivalent to having a different prior compared to the T.2 task for the same data distribution, i.e.:
theta ~ scale^2 * N(0, 1) = N(0, scale^2)
x ~ N(theta, scale * 1)

maybe im also missing something but i would be glad for clarification. _I also wanted to ask what code you used for the multivariate dataset from your paper part 3.3?_

https://github.com/stefanradev93/BayesFlow/blob/5ff1c1ea8ee2bda8cf333ae2890b95d05185af23/bayesflow/benchmarks/gaussian_linear_uniform.py#L85

**Comment by stefanradev93** [comment]
Hi Niels,

the task T2 in the BayesFlow repo is the same as the one in Lueckmann et al., only written slightly differently in code. :)
`numpy` parameterizes the normal with its scale, not its variance. 
Also, I think you are referring to task T1, since T2 has a uniform prior over the locations. 

Can you also please specify which paper you mean?

**Comment by stefanradev93** [comment]
Follow up: You are right in assuming that the default scaling factor in the BayesFlow differs from Lueckmann et al., since the 0.1 in the original paper is a variance and not a scale!

**Comment by stefanradev93** [comment]
Thanks for spotting the bugs! These are now fixed in the dev branch (soon to become main) and pointers to potential inconsistencies between paper and the two implementations have been added. I will resolve the issue upon a "thumbs up".
