### ISSUE TITLE
Softmax parameter cannot be recovered 

### ISSUE THREAD

**Issue by xiaozhi2** [stefanradev93/BayesFlow#70]
Hi,
Thanks for providing this amazing tool! I have tried to fit a cognitive model with Softmax as the choice rule in the end. That is, P(option i) = exp(beta * Ui) / [sum(exp(beta * Uj)) for all j]; However, I cannot recover parameter beta; 
I tried several minimal example with two options; and find that it seems exp(x1)/(exp(x1)+exp(x2)) is considered similarly as x1/(x1+x2); so when you have parameter beta in the latter case, it won't be able to be recovered; 
Do you know what causes this and how to solve it? Thanks in advance!

**Comment by stefanradev93** [comment]
Hi Xiaozhi,

it is possible that the softmax temperature parameter cannot be recovered, especially if U_j are also parameters in the model. The latter could potentially introduce some identifiability issues. I remember that @LuSchumacher had some problems with similar models, so perhaps we can have his take as well. What is the full model specification?

Note, that recoverability often has more to do with how you parameterize the model rather than which neural architecture / training scheme you employ.

**Comment by LuSchumacher** [comment]
Hi Xiaozhi,

I used BayesFlow for different RL model implementations (e.g., [VSE model](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006989) ) with Softmax as the choice rule and was able to recover the temperature parameter quite well. I used the following parameterization and priors:

`tau = np.random.uniform(0, 3) # prior for softmax temperature`
`chi = 3**tau - 1 # transform temperature parameter`
`e_x = np.exp(weights * chi)`
`action_prob = e_x / e_x.sum()`

Let me know if this solved your issue.

**Comment by xiaozhi2** [comment]
Thanks! it seems work okay when I tried the minimal example : `resp = np.random.choice(list(range(16)),  p =_softmax(chi*val))` where val is a fixed 500*16 array (known input). However, when I random sample 100 rows from val array each time, and train the model, it didn't work. Do you know why this happen?  It may be also helpful if I can see how you set the neural architecture and training scheme. Thanks a lot already!!

**Comment by xiaozhi2** [comment]
Here is my code: 
`def _softmax(x):
    """
    softmax function
    """
    e_x = np.exp(x)
    return e_x / e_x.sum()


def trial(val,ndt,tau):
    """Generates a response time and choice for a minimal example """
    # get number of decision alternatives
    rt = 3 +ndt
    chi = 3**tau - 1
    resp = np.random.choice(list(range(6)),  p =_softmax(chi*val))
    
    return rt, resp

def experiment(theta, val,*args):
    n_alt = 6
    # Sample 100 rows
    n_samples = 100
    sample_indices = np.random.choice(val.shape[0], n_samples, replace=False)

    out = np.zeros((500, 2))
    
    for n in range(500):
        out[n, :] = trial(vals[n],theta[-2], theta[-1])
    return out
`

**Comment by stefanradev93** [comment]
Can you post your full generative model setup (i.e., prior along simulator)?

**Comment by xiaozhi2** [comment]
Sure! Here they are:

`
def _softmax(x):
    """
    softmax function
    """
    e_x = np.exp(x)
    return e_x / e_x.sum()
`

`
def trial(val,ndt,tau):
    rt = 3 
    chi = 2**tau - 1
    resp = np.random.choice(list(range(6)),  p =_softmax(chi*val))
    return rt, resp
`

`
RNG = np.random.default_rng(2023)
np.set_printoptions(suppress=True)
`

`
def prior():
    ndt = RNG.uniform(0.0, 1.0) #RNG.gamma(1.5, 1/5.0)
    tau = RNG.uniform(0.0, 3.0)  #RNG.uniform(0.0, 1.0)
    return np.hstack((ndt,tau))
`

`
def experiment(theta, *args):
    n_alt = 6  
    n_samples = 100  
    np.random.seed(42)
    vals_all = np.random.rand(1000, n_alt)
    sample_indices = np.random.choice(vals_all.shape[0], n_samples, replace=False) 
    vals = vals_all[sample_indices]
    out = np.zeros((100, 2))  
    for n in range(100):  
        out[n, :] = trial(vals[n],theta[-2], theta[-1])  
    return out
`

`
simulator = bf.simulation.Simulator(
    simulator_fun=experiment)
`

`
model = bf.simulation.GenerativeModel(
    prior=prior,
    simulator=simulator,
    name='minimal_exp')
`

`
def configurator(forward_dict): 
    # Prepare placeholder dict
    out_dict = {}
    # Get simulated data and context
    data = forward_dict['sim_data']
    # one-hot encoding choices
    categorical_resp = to_categorical(data[:, :, 1])
    # concatenate rt, resp, context
    out_dict['summary_conditions'] = np.c_[data[:, :, :1], categorical_resp].astype(np.float32)
    # Get data generating parameters
    params = forward_dict['prior_draws'].astype(np.float32)
    # Standardize parameters
    out_dict['parameters'] = (params - prior_means) / prior_stds
    return out_dict
`
