### ISSUE TITLE
Wrong R^2 in bayesflow.diagnostics.true_vs_estimated()

### ISSUE THREAD

**Issue by marvinschmitt** [stefanradev93/BayesFlow#9]
The scatterplot function `bayesflow.diagnostics.true_vs_estimated()` displays incorrect values for the explained variance `R^2`, i.e. values greater than 1.0 and less than -1.0.

**Comment by zijianwang2000** [comment]
Hi Stefan,

I just wanted to ask whether this bug has been fixed yet, since I had the same problem (R^2 score can be less than -1.0) using the current version of bayesflow.

Best regards
Zijian
