### ISSUE TITLE
Regarding-your-joss-submission

### ISSUE THREAD

**Issue by sandeshkatakam** [stefanradev93/BayesFlow#96]
Link to the joss review issue : 
[https://github.com/openjournals/joss-reviews/issues/5702](https://github.com/openjournals/joss-reviews/issues/5702)
This issue is regarding your submission of the software paper BayesFlow to JOSS. I was trying to run the tests you mentioned in the tests folder using pytest. I am encountering the error because of the pyproject.toml file(this line in particular --cov BayesFlow). Can you please look into it once and respond.

**Comment by marvinschmitt** [comment]
Thank you for opening this issue.

Could you please try to install `pytest-cov` for the coverage metrics and see whether that resolves the issue?

```
pip install pytest-cov
```


Thanks,
Marvin

**Comment by yannikschaelte** [comment]
Hi @sandeshkatakam , the prerequisites for development should also be described here: https://bayesflow.org/contributing.html#environment

Specifically, running `pip install -r requirements_dev.txt` should install all necessary dependencies. @marvinschmitt it seems https://github.com/stefanradev93/BayesFlow/blob/Development/requirements_dev.txt could be updated, esp. to only require `>=` minimum versions?

**Comment by stefanradev93** [comment]
I have updated `requirements_dev.txt` in `Development` to use at least the recent versions of the listed packages (`>=`) .

**Comment by sandeshkatakam** [comment]
Thank you. The tests are running fine now.
