### ISSUE TITLE
JOSS review: citations missing

### ISSUE THREAD

**Issue by LoryPack** [stefanradev93/BayesFlow#97]
https://github.com/stefanradev93/BayesFlow/blob/45389ad93ae07582ffb1249f407ab09c1b49c6de/JOSS/paper.md?plain=1#L83

I believe the paper should also cite ABCpy here: https://github.com/eth-cscs/abcpy, with paper [here](https://www.jstatsoft.org/article/view/v100i07)

Related to https://github.com/openjournals/joss-reviews/issues/5702

**Comment by stefanradev93** [comment]
@LoryPack Thanks for pointing us at the ABCpy library! I have now added the appropriate .bib entry and reference in the text.

**Comment by LoryPack** [comment]
Thank you very much!
